### PR TITLE
Add native nlmixr2 support

### PR DESCRIPTION
**Pull request by mattfidler**
Hi @kylebaron 

After talking at ACoP about this package with Sam, something like was suggested, so I am starting a pull request.

I was going to add at test and consider if adding `pde` and `cwres` on the fly would work.

Also, the current best practice is to use `pde` instead of `npde` (I can reference the paper if you wish).  Can you add `pde` as an output option?

### CODE REVIEW

**Comment by mattfidler** [comment]
Also this seems to fail:

Before commit:

```
══ Results ══════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 22.2 s

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 332 ]
```

After has the same failures:

```
Duration: 22.8 s

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 332 ]
``` 

So it seems to me that there isn't any additional issue introduced by this pull request.

**Comment by mattfidler** [comment]
My guess is the new version of `ggplot2` `3.4` is to blame here.

**Comment by mattfidler** [comment]
Running examples gives:

```
1: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.
ℹ The deprecated feature was likely used in the pmplots package.
  Please report the issue at <https://github.com/metrumresearchgroup/pmplots/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

**Comment by mattfidler** [comment]
Also:

```
  Ignoring unknown parameters: `width`
```

Which probably comes from the new `linewidth` in `ggplot2` (yea)

**Comment by kyleam** [comment]
@mattfidler gh-71 (unmerged) should resolve these ggplot2 issues.

**Comment by mattfidler** [comment]
Ok.  Well this is ready.

For now I will not add `cwres` or `npde` if not present in the fit.

**Comment by kylebaron** [comment]
Hi @mattfidler  - 

Thanks for reaching out with this idea.  I'm sorry this fell of the radar and the PR got closed; we moved away from using the `develop` branch and I didn't appreciate this was still hanging out there and would get closed when the branch was deleted. I didn't give a lot of interaction on the PR but didn't intend to close without comment either. 

Some thoughts:

I think the proposed changes go a little deeper into the package than we'd like to see. I know it's nice when you can just pass this fit object into `cwres_time()` or whatever and get the diagnostics out. We designed this to take a data frame without any special class so the functions would work with a variety of modeling tools (still, obviously, requiring stuff like `TIME` and `NPDE` to be in the data). So I wonder if there was just a connector that you could maintain in nlmixr2 that would turn the fit object into a data frame that is compatible with the pmplots function set, it could easily allow access to all the functions. 

```r
nlmixr2extra::theoFitOde %>% 
  pmplots_nlmixr2_data() %>% 
  cwres_time()
```

or just coerce it once 

```r
new_dat <- pmplots_nlmixr2_data(nlmixr2extra::theoFitOde)

cwres_time(new_dat)
```

This is actually how we work with the package; we have a modeling object that we use to realize a data frame that can go into any downstream package that accepts a  data frame. 

Curious if you are still using `pde` in your modeling and simulation outputs? We don't currently and I'm not sure how widespread it is. But definitely something we could consider. 

Thanks,
Kyle

**Comment by mattfidler** [comment]
Yes, we use `PDE` over `NPDE` in our outputs.  There is a paper that states that `PDE` do not have strange autocorrelation effects that `NPDE` does.

In Monolix `PDE`=`NPDE`, though in `saemmix`, `NONMEM` and `nlmixr2` this is not true.

Often we have seen EU regulatory requests for `PDE` plots.

**Comment by mattfidler** [comment]
I will not maintain the ` pmplots_nlmixr2_data()` in `nlmixr2` core, since I don't maintain the interface for `ggPMX` or `xpose` there.

**Comment by mattfidler** [comment]
The function may be too small for a stand alone package too.  I will ask the nlmixr2 team and see if they want to support a connector package.

**Comment by seth127** [comment]
Hi @mattfidler (this is Seth Green, Manager of Data Science Engineering at MetrumRG.)

I see your point that this function doesn't clearly fit on either side, but is also too small to really justify it's own package.

What would you think about a simple "data extractor" function in `nlmixr2`? Something similar to what you propose here, but not specific to `pmplots`, maybe like

```r
nlmixr2_data <- function(data, type=c("left", "inner", "right")) {

  if (inherits(data, "<someOtherFitObject>")) { 
    # convert to an nlmixr2FitData object...
  }

  if (inherits(data, "nlmixr2FitData")) { 
    type <- match.arg(type)
    return(switch(type,
                  left=data$dataMergeLeft,
                  inner=data$dataMergeInner,
                  right=data$dataMergeRight))
  }
  data
}
```

...or use some kind of method dispatch if you'd prefer. Either way, that would facilitate the pattern @kylebaron described above, something like:

```r
nlmixr2extra::theoFitOde %>% 
  nlmixr2_data() %>% 
  cwres_time()
```

...but could also be useful for passing that data tibble on to various other processes.

I looked through some of the nlmixr-related repos a bit to see if you already have a method like this (for extracting the model data as a tibble) but I didn't see it. Apologies if I missed it.

**Comment by kylebaron** [comment]
Thanks for the info on `PDE`; we hadn't come across a request for that yet, but I guess we will at some point. 

> I looked through some of the nlmixr-related repos a bit to see if you already have a method like this (for extracting the model data as a tibble) but I didn't see it. 

Now I'm not sure where this object is coming from; but I think whatever package is originating that class should also be issuing a method to get it into regular data frame like format. Is that reasonable?

**Comment by mattfidler** [comment]
To me the only value of the pull request was what you mentioned before:

> ...  you can just pass this fit object into cwres_time() or whatever and get the diagnostics out.

In fact is a little more nuanced because in most cases you can do that directly with a `nlmixr2` fit but (since it is a data-frame with attributes and methods attached).  So if you do not want covariates or the like you can simply use:

```r
nlmixr2extra::theoFitOde %>% 
  cwres_time()
```

The method above only expands to the fit to have covariates from the original dataset and not necessarily  in the fit output.

> Now I'm not sure where this object is coming from; 

This is simply an autogenerted nlmixr2 fit saved for package testing (so you don't actually have to do a fit for testing).

> but I think whatever package is originating that class should also be issuing a method to get it into regular data frame like format. Is that reasonable?

The method already gives a regular data-frame format for this data.  

If you use the `$dataMergeLeft` method,  you could do this as well:

```r
nlmixr2extra::theoFitOde$dataMergeLeft |>
  cwres_time()
```

The pull just takes the cognitive burden away from users about the extra step needed to generate covariate type plots.

In my opinion the `nlmixr2_data()` function would be redundant to the methods that were used in the `nlmixr_data()` and  [already exist.] (https://github.com/nlmixr2/nlmixr2est/blob/b2f4cea417000b19c034d0306f880844d682ac66/R/nmObjGet.R#L343-L481) 

If you want to only accept `data.frame` objects then there is nothing else to do.

**Comment by kylebaron** [comment]
>If you want to only accept data.frame objects then there is nothing else to do.

Got it, @mattfidler ; thanks for clarifying the intent. I think this is what we want to continue to do - asking the conversion / coercion to happen upstream and take data frame from any tool. 

BTW ... I did go ahead and open a PR that adds a set of functions for plotting `NPD`; still wip but it is ip. 

Kyle

**Comment by mattfidler** [comment]
Thanks Kyle

**Pull request closed without merging**
